[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/torn-organised-crimes-manager.jar"
restartPolicyType = "never"  # Important for cron jobs - don't restart on exit

[environments.production]
variables = {}